packages:
  - 'packages/*'
  - 'vscode'

catalog:
  '@types/node': '^22.13.14'
  '@types/semver': '^7.7.0'
  '@types/vscode': '^1.98.0'
  # valor
  '@volar/language-core': '~2.4.12'
  '@volar/language-server': '~2.4.12'
  '@volar/language-service': '~2.4.12'
  '@volar/typescript': '~2.4.12'
  '@volar/vscode': '~2.4.12'
  '@vue/compiler-dom': '^3.5.0'
  '@vue/shared': '^3.5.0'
  # common
  'reactive-vscode': '^0.2.14'
  'typescript': 'latest'
