packages:
  - packages/*
  - vscode
  - inspect-extension

catalog:
  '@mpxjs/core': latest
  '@volar/language-core': ~2.4.12
  '@volar/language-server': ~2.4.12
  '@volar/language-service': ~2.4.12
  '@volar/typescript': ~2.4.12
  '@volar/vscode': ~2.4.12
  '@vue/compiler-dom': ^3.5.0
  '@vue/shared': ^3.5.0
  '@types/node': ^22.13.14
  '@types/path-browserify': ^1.0.1
  '@types/semver': ^7.7.0
  path-browserify: ^1.0.1
  reactive-vscode: ^0.2.14
  typescript: latest
  vscode-uri: 3.1.0
