name: Publish Extension

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build && pnpm -F mpx-official bundle

      - uses: actions/github-script@v7
        id: checkPrerelease
        name: Check if prerelease
        with:
          script: |
            const version = context.ref.replace('refs/tags/v', '').split('.');
            core.setOutput('preRelease', String(version[1] % 2 !== 0))

      - name: Publish to Visual Studio Marketplace
        id: publishToVSMarketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          preRelease: ${{ steps.checkPrerelease.outputs.preRelease == 'true' }}
          pat: ${{ secrets.VSCE_PAT }}
          packagePath: './vscode'
          registryUrl: https://marketplace.visualstudio.com
          dependencies: false

      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          extensionFile: ${{ steps.publishToVSMarketplace.outputs.vsixPath }}
          pat: ${{ secrets.OPEN_VSX_PAT }}
